### ISSUE TITLE
フォント名

### ISSUE THREAD

**Issue by munyagu** [ixkaito/NotoSerifCJKjp-subset#1]
「Noto」は予約されたフォント名と思います。
（https://www.google.com/get/noto/ に Noto is a trademark of Google Inc. と記載されています）

配布されているフォント名が
「Noto Serif CJK JP Medium」
となっています。
（NotoSerifCJKjp-Medium.otf を確認しました）

SIL Open Font Licenseには
「3）フォントソフトウェアの改変バージョンで、予約されたフォント名を使用することは、その著作権所有者が書面による明示的な許可を与えていない限りできない。この制限はユーザーに示される主要なフォント名だけに適用される。」
とありますが、配布されているフォントファイルを私が利用したり、再配布しても問題はないでしょうか？

**Comment by ixkaito** [comment]
@munyagu 確認ありがとうございます。

Noto は Reserved Font Name ではないと思います。[Google Fonts - Attribution](https://fonts.google.com/attribution) を確認すると、"with Reserved Font Name" の記載はございません。[こちらのライセンス](https://github.com/googlei18n/noto-cjk/blob/master/LICENSE)にも記載はございません。

念の為 Google に問い合わせましたところ、「違うと思う。使っていいよ。」とのことでした 🙂

ということなので、

> 配布されているフォントファイルを私が利用したり、再配布しても問題はないでしょうか？

もちろんかまいません。

**Comment by munyagu** [comment]
回答ありがとうございます。
ありがたく使わせて頂きます。
お手数をおかけしました。
